### ISSUE TITLE
about the time prob

### ISSUE THREAD

**Issue by Mobzhang** [urielsinger/CTDNE#1]
I have a question about if two nodes which have more than one time edge, how should the trans prob calculate ? fouce the latest time edge?

**Comment by urielsinger** [comment]
As mentioned in the paper, multiple edges are treated as different edges. This means that a temporal random walk has different edges to walk on to get to the same neighbor (if it has multiple edges to him).
Please notice that the multiple edges might have different timestamps, creating a different probability to walk on each edge..

**Comment by Mobzhang** [comment]
thank u !

**Comment by urielsinger** [comment]
You're welcome!
